# Generated by Django 4.2.4 on 2023-09-02 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
